language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
services:
  - mongodb
before_script:
  - sleep 5  # wait for mongoDB to accept connections
  - ./tests/db_init.sh
script:
  - mongo test_db --eval 'db.test_col.count() == 25359;'
  - python setup.py install
  - py.test tests
after_success:
  - coveralls